version: '2'

services:
  fs-server:
    image: "causticlab/filesync:dev"
    tty: true
    stdin_open: true
    labels:
      io.rancher.scheduler.affinity:host_label: filesync=server
    environment:
      FILESYNC_MODE: 'server'
      FILESYNC_PATH: '/share'
    volumes:
      - ./demo/server:/share
  fs-client1:
    image: "causticlab/filesync:dev"
    tty: true
    stdin_open: true
    links:
      - fs-server:fs-server
    labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.scheduler.affinity:host_label_ne: filesync=server
    environment:
      FILESYNC_MODE: 'client'
      FILESYNC_IP: 'fs-server'
      FILESYNC_PATH: '/share'
    volumes:
      - ./demo/client1:/share
  fs-client2:
    image: "causticlab/filesync:dev"
    tty: true
    stdin_open: true
    links:
      - fs-server:fs-server
    labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.scheduler.affinity:host_label_ne: filesync=server
    environment:
      FILESYNC_MODE: 'client'
      FILESYNC_IP: 'fs-server'
      FILESYNC_PATH: '/share'
    volumes:
      - ./demo/client2:/share